name: cpp

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: sudo apt-get install libglu1-mesa-dev mesa-common-dev libsdl2-dev
    - name: cmake
      run: cmake .
    - name: make
      run: make

