name: wasm

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: lovasoa/setup-emscripten@master
    - name: deps
      run: sudo apt-get install libglu1-mesa-dev mesa-common-dev
    - name: folder
      run: |
        mkdir wasm
        cd wasm
    - name: cmake
      run: emconfigure cmake ..
    - name: make
      run: make
