name: wasm

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: lovasoa/setup-emscripten@master
    - name: deps
      run: sudo apt-get install libglu1-mesa-dev mesa-common-dev
    - name: build
      run: |
        mkdir wasm
        cd wasm
        emconfigure cmake ..
        make
